"use strict";

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("clients", [
      {
        // id: 1,
        first_name: "Jon",
        last_name: "Snow",
        phone_number: 12345678,
        email: "jon@snow.com",
        password: "Password123",
        photo_link: "abc",
        age_client: 29,
        gender: "Male",
        marital_status: "Single",
        therapist_confirmed: false,
        gender_preference: "Female",
        description: "I am looking for help.",
        active: true,
        admin: false,
        created_at: "2022-09-10 10:30:09.410 +0900",
        updated_at: "2022-09-10 10:30:09.410 +0900",
        specialization_id: 2,
        age_id: 1,
        language_id: 3,
        religion_id: 1,
      },
      {
        first_name: "Ryoji",
        last_name: "Fuji",
        phone_number: 98765432,
        email: "ryoji@ryoji.com",
        password: "Password123",
        photo_link: "abc",
        age_client: 29,
        gender: "Male",
        marital_status: "Single",
        therapist_confirmed: true,
        gender_preference: "Female",
        description: "I need helpppp",
        active: true,
        admin: false,
        created_at: "2022-09-12 11:36:09.410 +0900",
        updated_at: "2022-09-12 11:36:09.410 +0900",
        specialization_id: 2,
        age_id: 2,
        language_id: 1,
        religion_id: 1,
        dailymood: 3,
      },
      {
        first_name: "HELPP",
        last_name: "MEEEEE",
        phone_number: 23456789,
        email: "help@me.com",
        password: "Password123",
        photo_link: "abc",
        age_client: 40,
        gender: "Female",
        marital_status: "Married",
        therapist_confirmed: true,
        gender_preference: "Female",
        description: "helpmepls",
        active: true,
        admin: false,
        created_at: new Date(),
        updated_at: new Date(),
        specialization_id: 2,
        age_id: 2,
        language_id: 1,
        religion_id: 1,
        dailymood: 4,
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("clients", null, {});
  },
};
