"use strict";

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("clients", [
      {
        // id: 1,
        first_name: "Jon",
        last_name: "Snow",
        phone_number: 12345678,
        email: "jon@snow.com",
        password: "Password123",
        photo_link:
          "https://johnbealrealestate.com.au/wp-content/uploads/Jon-Snow-Winter-is-Coming.jpg",
        age_client: 40,
        gender: "Male",
        marital_status: "Single",
        therapist_confirmed: false,
        gender_preference: "Male",
        description: "Winter is coming...So is my midlife crisis.",
        active: true,
        admin: false,
        created_at: "2022-09-10 10:30:09.410 +0900",
        updated_at: "2022-09-10 10:30:09.410 +0900",
        specialization_id: 2,
        age_id: 4,
        language_id: 1,
        religion_id: 1,
        dailymood: 2,
      },
      {
        first_name: "Ryoji",
        last_name: "Fujinami",
        phone_number: 98765432,
        email: "ryoji@ryoji.com",
        password: "Password123",
        photo_link:
          "https://media-exp1.licdn.com/dms/image/C5603AQGOlih8HDynAg/profile-displayphoto-shrink_800_800/0/1656691562897?e=1669852800&v=beta&t=tDKfoWOMMYBlCvKzTyAZka3JFfRhaibHAXAfvLyPwVc",
        age_client: 29,
        gender: "Male",
        marital_status: "Single",
        therapist_confirmed: true,
        gender_preference: "Male",
        description: "I need helpppp!!!!! HELP MEEEEE!!!",
        active: true,
        admin: false,
        created_at: "2022-09-12 11:36:09.410 +0900",
        updated_at: "2022-09-12 11:36:09.410 +0900",
        specialization_id: 3,
        age_id: 4,
        language_id: 1,
        religion_id: 1,
        dailymood: 3,
      },
      {
        first_name: "Sam",
        last_name: "O'Shaughnessy",
        phone_number: 23456789,
        email: "samo@samo.com",
        password: "Password123",
        photo_link:
          "https://media-exp1.licdn.com/dms/image/C5103AQG8gJeKyT4R1Q/profile-displayphoto-shrink_800_800/0/1567646854757?e=2147483647&v=beta&t=s2mvD3n1OyosgfsRRLlfUh0EVRcKYjcmXP5MxiCtXE4",
        age_client: 29,
        gender: "Male",
        marital_status: "Married",
        therapist_confirmed: true,
        gender_preference: "Male",
        description: "I do not actually need help",
        active: true,
        admin: false,
        created_at: new Date(),
        updated_at: new Date(),
        specialization_id: 5,
        age_id: 4,
        language_id: 1,
        religion_id: 1,
        dailymood: 1,
      },
      {
        first_name: "Anya",
        last_name: "Forger",
        phone_number: 314159269,
        email: "anya@forger.com",
        password: "Password123",
        photo_link:
          "https://aniyuki.com/wp-content/uploads/2022/05/aniyuki-anya-forger-image-55.jpg",
        age_client: 6,
        gender: "Female",
        marital_status: "Single",
        therapist_confirmed: true,
        gender_preference: "Female",
        description:
          "Anya can read minds! Anya wants to become a spy like my father and an assassin like my mother!!! WAKU WAKU",
        active: true,
        admin: false,
        created_at: "2022-09-26 11:36:09.410 +0900",
        updated_at: "2022-09-26 11:36:09.410 +0900",
        specialization_id: 5,
        age_id: 3,
        language_id: 1,
        religion_id: 2,
        dailymood: 1,
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("clients", null, {});
  },
};
